name: Build all driver samples
on:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - '**.md'
      - 'LICENSE'
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        configuration: [Debug, Release]
        platform: [x64, arm64]
    runs-on: windows-2022
    env:
      Solution_Path: general\echo\kmdf\kmdfecho.sln
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Retrieve and build all available solutions
        id: build-all-projects
        run: |
          .\Build-AllProjects.ps1
        env:
          Configuration: ${{ matrix.configuration }}
          Platform: ${{ matrix.platform }}
